services:

  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./src:/app
      - ./.env.example:/tmp/.env.example
    working_dir: /app
    depends_on:
      - db
  
  web:
    image: nginx:1.28.0
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    container_name: db
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'

  node:
    image: node:22.16
    container_name: node
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "5173:5173"
    tty: true
    depends_on:
      - app
    command: >
      sh -c "while [ ! -f package.json ]; do echo 'Waiting for package.json...'; sleep 2; done; npm install; tail -f /dev/null"


volumes:
  db-store:
